name: Build and Release HAR

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - 'entry/entry.html'
      - 'payloads/**'
      - 'autoxss.js'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run HAR Build
        run: npm run har-build

      - name: Get HAR filename
        id: get-har
        run: |
          HAR_FILE=$(ls *.har | sort | tail -n 1)
          echo "har_file=${HAR_FILE}" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-har
          name: Hartools
          files: ${{ steps.get-har.outputs.har_file }}
          body: |
            # Instructions:

            1. **Download the latest `.har` file** attached.
            2. **Get the `.har` file** onto the device you want to run the DevTools XSS on.
            3. On the target device, go to:  
               `devtools://devtools/bundled/inspector.html`  
               > If blocked, try one of the following:  
               > - `devtools://devtools/bundled/js_app.html`  
               > - `devtools://devtools/bundled/devtools_app.html`  
               > - `devtools://devtools/bundled/worker_app.html`  
            4. Once fully loaded, append `?experiments=true` to the URL and press Enter.  
               Example: `devtools://devtools/bundled/inspector.html?experiments=true`
            5. Go to the **Network** tab. If it’s not visible, click `>>` on the topbar and select **Network**.
            6. Click the upload icon 📤 and upload the `.har` file.  
               > You may need to expand the sidebar to see the upload button.
            7. **Double-click** the text that appears — `[DOUBLE CLICK THIS]` — to trigger the payload.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
